theme: jekyll-theme-cayman

title: Youth For Bernie
description: Getting the young generation on board to vote for our next President!
show_downloads: "true"
# google_analytics: [Your Google Analytics tracking ID]


github:
  "url": "youthforbernie.com",
  "repository_url": "https://github.com/Youth4Bernie/youth4bernie.github.io",
  "repository_nwo": "Youth4Bernie/youth4bernie.github.io"
  
